"use client";

import {
    ResponsiveContainer,
    BarChart,
    Bar,
    XAxis,
    YAxis,
    Tooltip,
    CartesianGrid,
    LabelList,
} from "recharts";

import { AssessmentReport } from "@/types/report";

interface Props {
    data: AssessmentReport;
}

export default function ImpactChart({ data }: Props) {
    const chartData = [
        {
            metric: "Cost Savings",
            value: data.metrics.costSavings,
        },
        {
            metric: "Revenue Impact",
            value: data.metrics.revenueImpact,
        },
    ];

    return (
        <section
            className="
                p-8
                rounded-3xl
                border
                border-zinc-800
                bg-zinc-900/20
            "
        >
            <h2 className="text-2xl font-bold mb-2">
                Predicted Business Impact
            </h2>

            <p className="text-zinc-500 mb-8">
                Expected financial outcomes generated by the ML assessment engine.
            </p>

            <div className="h-[350px]">
                <ResponsiveContainer width="100%" height="100%">
                    <BarChart
                        data={chartData}
                        margin={{
                            top: 20,
                            right: 20,
                            left: 50,
                            bottom: 10,
                        }}
                    >

                        <CartesianGrid
                            strokeDasharray="3 3"
                            stroke="#27272a"
                        />

                        <XAxis
                            dataKey="metric"
                            stroke="#a1a1aa"
                        />

                        <YAxis
                            stroke="#a1a1aa"
                        />

                        <Tooltip
                            formatter={(value) =>
                                `$${Number(value).toLocaleString()}`
                            }
                            cursor={{
                                fill: "transparent",
                            }}
                            contentStyle={{
                                backgroundColor: "#18181b",
                                border: "1px solid #27272a",
                                borderRadius: "12px",
                                color: "#ffffff",
                            }}
                            labelStyle={{
                                color: "#ffffff",
                            }}
                        />

                        <Bar
                            dataKey="value"
                            fill="#22c55e"
                            radius={[8, 8, 0, 0]}
                        >
                            <LabelList
                                dataKey="value"
                                position="top"
                                formatter={(value) =>
                                    `$${(Number(value) / 1000000).toFixed(1)}M`
                                }
                                fill="#ffffff"
                            />
                        </Bar>

                    </BarChart>
                </ResponsiveContainer>
            </div>

        </section>
    );
}